{
  'language': node_js,
  'os': ['linux'],
  'dist': 'xenial',
  'node_js': ['13'],
  'cache': { 'directories': ['node_modules'] },
  'install': ['npm install'],
  'script': ['npm run deploy'],
  'deploy':
    [
      {
        'provider': 'pages',
        'strategy': 'git',
        'repo': 'github.com/JasonToups/werk',
        'on': { 'branch': 'master' },
        'name': 'jason-toups',
        'email': 'me@jasontoups.com',
        'local_dir': 'docs',
        'skip_cleanup': true,
        'token': '$GITHUB_TOKEN',
        'keep_history': true,
        'target_branch': 'master',
      },
    ],
}
